// The entries for the Bingo. May be modified but must be 
// at least 24 entries.
let bingoEntries = new Array(
	"Attention - Color", 
	"Attention - Movement", 
	"Color theory - Harmony",
	"Visual search pop out - Color",
	"Visual search pop out - Shape",
	"Gestalt Rule - Common Region",
	"Gestalt Rule - Proximity",
	"Short-term memory",
	"7 &plusmn; 2 Memory",
	"Fitt's Law",
	"Mental model",
	"Metaphor",
	"Affordance",
	"Gulfs of Execution and Evaluation",
	"Nielsen's: Visibility of System Status", 
	"Nielsen's: Match Between System and the Real World", 
	"Nielsen's: Consistency and Standards", 
	"Nielsen's: Flexibility and Efficiency of Use", 
	"Nielsen's: Aesthetic and Minimalist Design", 
	"Nielsen's: Error Prevention", 
	"Nielsen's: Recognition Rather Than Recall",
	"Nielsen's: Help Users Recognize, Diagnose, and Recover from Errors", 
	"Nielsen's: Help and Documentation",
	"Gamification");

	// "Learnability - Predictability (past interactions /w the tech inform future actions)",
	// "Learnability - Familiarity (past interactions outside the tech inform future actions)",
	// "Learnability - Consistency",
	// "Flexibility - Substitutivity (can perform a task using more than one way)",
	// "Flexibility - Multi-threading",
	// "Flexibility - Dialog Initiative (let users initiate the dialog with the technology)",
	// "Robustness - Recoverability (users can correct the errors)",
	// "Robustness - Visibility (users are clear about what the system can do)",
	// "Robustness - Transparency (tells the user about what has been done)",
	// "Robustness - Observability",
